title: Oliver Scheiwiller
logo: /assets/img/oschei.jpg
detailed: detailed.html
intro: Hello, my name is Oliver. Iâ€™m a Senior Project Manager at Scandit in Switzerland. My interests include human-computer interaction, ethics in computing, accessible design, technology assisted learning, and machine learning.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/oschei/
github_url: https://www.github.com/oschei