title: Oliver Scheiwiller
logo: /assets/img/oschei.jpg
detailed: detailed.html
intro: "Hello, my name is Oliver! Iâ€™m the Enterprise Architect @ Scandit. My interests include human-computer interaction, ethics in computing, accessible design, and technology assisted learning."
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
linkedin_url: https://www.linkedin.com/in/oschei/
github_url: https://www.github.com/oschei